### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by Epikem** [interpreters/pypreprocessor#11]
Thank you for fast response. But still I can't install. Output is below.

PS xx> pip install pypreprocessor
Collecting pypreprocessor
  Using cached pypreprocessor-0.72.tar.gz
    Complete output from command python setup.py egg_info:
    Pypandoc not installed, skipping README.rxt creation
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "xx\pip-build-vjy1r10x\pypreprocessor\setup.py", line 31, in <module>
        license = open('LICENSE').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

I successfully installed lower versions before, and definitely LICENSE file exists in this repository. But was not in pip tar.gz. Maybe pip removed it.

**Comment by evanplaice** [comment]
Yep, I recently changed over from disttools to setuptools and there are some subtle differences between the two. Just pushed 0.7.3 with the fix.

Let me know if you're still having issues.

**Comment by Epikem** [comment]
It installed successfully. Thanks!
pip install pypreprocessor
Collecting pypreprocessor
  Downloading pypreprocessor-0.7.3.tar.gz
Building wheels for collected packages: pypreprocessor
  Running setup.py bdist_wheel for pypreprocessor ... done
  Stored in directory: xx\Cache\wheels\48\b5\dc\3b3b8c1b0e1ea3404f9fb6dac32acff9ac8d6c5ba57d048c3c
Successfully built pypreprocessor
Installing collected packages: pypreprocessor
Successfully installed pypreprocessor-0.7.3

**Comment by evanplaice** [comment]
Thank you for your patience. Glad I could help.
