### ISSUE TITLE
Windows python 2 IOError randomly occurs while parsing

### ISSUE THREAD

**Issue by Epikem** [interpreters/pypreprocessor#14]
Environment : Windows 10, Python 2.7 (virtualenv)

When I run tests, strange error occurs.

<pre>
> <b>python .\setup.py test</b>
Pypandoc not installed, skipping README.rst creation
running test
Test Start
test_norun_noresume_nosave (tests.maintest.FileParseTest) ... ok
test_norun_noresume_save (tests.maintest.FileParseTest) ... ok
test_norun_resume_nosave (tests.maintest.FileParseTest) ... ok
test_norun_resume_save (tests.maintest.FileParseTest) <b>error: [Errno 0] Error</b>
</pre>

It also occurs lastest release.

<pre>
PS D:\Users...\tests\.isolated> <b>python .\directivetest.py</b>
('Warning: Number of unclosed Ifdefblocks: ', 3)
Can cause unwished behaviour in the preprocessed code, preprocessor is safe
Do you want more Information? <b>'t'</b>
('Name of input and output file: ', '.\\directivetest.py', ' ', '')
('Block:'Traceback (most recent call last):
  File ".\directivetest.py", line 7, in <module>
    pypreprocessor.parse()
  File "D:\Users\...\.virtualenvs\psptoolsPython2\lib\site-packages\pypreprocessor\__init__.py", line 240, in parse
    print('Block:',item, ' is in condition: ',cond )
<b>IOError: [Errno 0] Error</b>
PS D:\Users\...\pypreprocessor\pypreprocessor\tests\.isolated> <b>pip list</b>
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pip (9.0.1)
pypreprocessor (0.7.3)
setuptools (38.5.1)
wheel (0.30.0)
</pre>

It occurs randomly and I couldn't find why it happens. It doesn't appear on some simple parse settings.
Below code seems minimal.
```python
import sys
from pypreprocessor import pypreprocessor

pypreprocessor.mode = 'ppcont'
pypreprocessor.parse()
print('Testing Python ' + sys.version[:3] + ':')

#define t1

#ifdef t1
print('t1')
#else
print('no t1')
#endif
```

<pre>PS D:\Users\...\pypreprocessor\pypreprocessor\tests\.isolated> <b>python .\test2.py</b>
Testing Python 2.7:
tTraceback (most recent call last):
  File ".\test2.py", line 11, in <module>
    print('t1')
<b>IOError: [Errno 0] Error</b>
</pre>

And if I change mode to 'run' it does not raised.

**Comment by evanplaice** [comment]
I can think of a few things worth trying.

Disable squelching and removeMeta so you can see the full output. Then see if you can redirect the output to the console or a file so you can see what it's producing.

With those 2 settings disabled you should be able to see the raw output of the parser, any lines marked to be excluded from the output will be commented out.

Does it still show the same error when you process to a file, or does this only happen when you use the preprocessor in self-consuming mode?

**Comment by Epikem** [comment]
Sorry it seems my environment problem. Failed to reproduce on other computer, install everything from first. And it even occurs on python interpreter for me on this pc. Maybe I should reinstall python.
